apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  encryptedData:
    smtp_auth_password: AgA7ZjtmPqHYGw7PaGDy01mBXIPSkV1qq50IB6JDlBXceTbrZZiDP6m5oucyXSH+sahkoo2e5MmAAuzNmk72LrQI7jIc+ELZ762IIQkp9iayvGwky/igFUOdEDfEfzvjaZfNn6pZ6tlQUGfOHo23vz1kEk7YZEwOFOkiUsez3w+JEewQJtpcXc6uVkZRYMM0R30zeetC0uHIF33uljG0nZE+5/CFGX/12YFN3r+yYKakfPVpaL6VpHWf/drr/bxO+Lfsc6h+ZOYHSbWII/4Ru9EGWnLQezy+FX+8XTzeAz8njqrOU+p+rSySRF08sLldcuL6JUQUNfPu5JSg7wzliOxkgUoQGG6tx/rK4LSHYq8/okCaymW07moFQf9kYih84DjJjzHEYrw+xcG3guclGg0UF/AsTBCQUeH/Qqzzhth86NlZrosjXlQBda9+aKjilcpl9HugDkb6V9OobJraP0nIDpfudVdUe0mHF7X4Eu2hlZFm/lNX5btgHeL8ovZ85aXqG7RaPD5AmW7XTK3Po0KkE/jGR2lnhMjDEfIm6tjBG/lyUvI0/fJQYtZl3T3XoGcvbInpyUY+WXpwWBIQNzrBrMgkuw1MBppR7Ya2haY3sCGArqPeno4C4eNV3QridryG+/LTAj7A8nDDFNMzwm/Y38RwPAcdhEMqfFLUJUnsplxofKRYmx6GatmltsL1F9xSg7V4pJ6GI15BR1r89/pX
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-smtp-secret
      namespace: monitoring
---
