apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  encryptedData:
    smtp_auth_password: AgBLXgeMtlujZ10FuwHGtbjbVIRwP+r2AvYozdtytsZ1Kqf+SZ3pyInqQL3ZrQ+FUxUvZC1fgjeqAvQBenPxtyDCf6J503/bRCtizkScZbOAJo1znKzE2yZl7ov3JgYzbrarwgp7hLLHMsPz+idrOE6txV9w18/AtyUS1ulGTCjmZ0tupa10i/Ydoah5w58hlTAzkhPa/vDi9Dw51f6H2bo2dgsnX34foYg2s0W+AmW6JsFKVSjNluNopev7MG5mLzXWQSVvgNXrMOjCL846p0MW+GAzdJGBVJs0UB4z6CG03QGDKvQ9eReEcICcf5pl1/r53dOJcYmuhDvAcS42EPKZehk6KuUrpLcqsPYGFcHstoENVSVvb8Qg/k4jiBgw5Jje4OZIH44ZahjSAJZAYnYGa3aKJM7eQLa86yFiyi7CFwdA3iRRBghyfzrLJedPrrXq7R7wnm7nXIdTtHDpXMybWbyOu2UUuiR8DKqPcF7DBQk4pli0usw8Ylpakq2QkvcOV9WaI+4nzh7gC9Ar8M2HmncaEwCLDb2HTF4Yn5Cgo9C2Gz0NmDRsWqtjrol9o5unpU//HeSZQgVOpkaviabzf7Dg5LjVGOkly0fl00EuxCca9iiwyi1GoYG/oWpkz0VTiLKNn4cdfd5Zi+SfUD0VsVE2QURnpATL1uiAAN7ooCJ+Uh/r0uipcZk96IzOxUFWeP0rsnwaFRbJV89R8Cxj
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-smtp-secret
      namespace: monitoring
---
