apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB5T/HgK2HBRS7Fz/NKoxucEXfbnk4ZBcThGMPZqy0aR1d+h2Sx61VMvfsZynAMaTRPpYJQUVwVgwrFjBPxUymZVfTMM2Y7WLJqyyvFwXRqT3DZh2CoLwlC4aAMiJit70b8+QpOXJii+7hQhwvzwUQsRF5PmXvhiFVQR56bl9ObfGg9otOEoV0N5r39EixXZ4cvR6coAzSidB5NjiXE2TyRt9sdAjH/KqceBsbk0/bueuJfSTr6AFlOVuy+R4E+balB0YvtFcgwxFAGB1Hvr4SOEMY6GkAmD9fiAwPse0T8K+kP5ZCwOxl8ezzDcyJiCljfesdXtZs3uKFno3Nww83WiGdglMLJpQuDTJ84zl+M8LR/F8W/cb9J8UAX1uWBfXgwrYIDrBXzXM7oOW7khUVBQnaXIO1EeYVEQNzzxxd8MtyzU5PnMw2SPXlRF35PAOgD1TxbBMXipNUYo4ajgViz0TbklhUefjXHomRMbLTEAU8xemboSkgdzXqk/g+Y4su+RAOWtmprG5F1dUZ//gIr1mv6V6L2YJecrKksg24mFQyHRLD3FNOVOcwzC4t912VEyPoEkrEfnjdsNoV+rBiwevsoyeFU5hGrraCOrYAGnW9zUZrlbRPBm3JmWdDBbfoq1RYkVsRnLyPMWzKjIi1H0hQ7NfAxBNt/ZxhWwgET7GbCOJPpZFiVoUdfVuN12EPu6Qvy7E3QHaMs+cveMCM=
    admin-user: AgBNM8nZMpNs3gkz2CZ78UgDbh8x3uj87pNbCRV/+3AvBzdkmQ0h50yc6m/1W9bTrsHJ6b9Pfxr6ql5Pzk5gJs2Bb9qpFdqKeqkckn2ypcl7U3m9gkOYfoEA26jr1yxKyOgzxJ5EaFUhSNJQFVvwuUtpIX7LI4ta/Xc1RnrPgT5Cf7GAlItlQESsM9HpH2dHDeauMvy+Ekj71O2YqzYbTq721XpEe0MNaLxrHqqFNr8dGgG5YVJ/k5FDSRLxLpzPMtGk9ppw3iLyqnaOAyLzzx8Jh1VttdD3CG+9Kkq98xkI9Jm1Wmwo+l5qDQC9Vw+1d5HAG2LCDpNhd+sbhkVXvD5803zYfbjoFdI1QqoUwaJB0rLKIcA8HDDbB6zaSldb19GL+vdegOg7BnWKEMInKlhEjRQksEdtgp47ftuDLNS44HgXXPyq3DwMOWDwVSTnCAuafr++8kgKqevMVg/c/Zafj+IbyA7hqeEqk9rbNV9R4ZZ452TjLD8+JfGEg9M/bziFeI9bdPxamBQcgn/6eW69Io3L/pmZ4lABMhnXf8pNeioyHXDfNQJLnUPFtKFC6v7I+doL+QjX+1cLI5sZSLMJzozR68DPf61fKHqBcXxoKmA/LWZEc55fZ/wUNDs5VWiRnOt/KH6U5R/ZJ/SdnWy9mGqN2rnzcb96R/MWtAk1LmUfmrY/wcOKH4XEo0wlO3GyAmWX+poFT+VV3A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
---
