grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.morguen.fr
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.morguen.fr
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

prometheus:
  prometheusSpec:
    retention: 15d

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'homelab.alerts.morguen@gmail.com'
      smtp_require_tls: true
      smtp_auth_username: 'homelab.alerts.morguen@gmail.com'
      smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-smtp-secret/smtp_auth_password
    route:
      receiver: 'email'
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: 'null'
      - name: 'email'
        email_configs:
          - to: 'homelab.alerts.morguen@gmail.com'
            send_resolved: true
    inhibit_rules:
      - target_matchers:
          - severity =~ warning|info
        source_matchers:
          - severity = critical
        equal: ['namespace', 'alertname']
  alertmanagerSpec:
    secrets:
      - alertmanager-smtp-secret

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeProxy:
  enabled: false
