apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "56.6.2"
    helm:
      valueFiles:
        - $values/platform/monitoring/values.yaml
  source:
    repoURL: https://github.com/TomGn1/Stack-GitOps---ArgoCD-Monitoring.git
    targetRevision: HEAD
    path: platform/monitoring
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
